version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: currency_bird_test
    ports:
      - "5432:5432"
    networks:
      - app-network

  # Express Server
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/currency_bird_test
    ports:
      - 4000:4000
    networks:
      - app-network
    restart: always
    volumes:
      - .:/app
      - ./prisma:/app/prisma
      - ./logs:/root/.npm/_logs

networks:
  app-network:
    driver: bridge
