version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: currency_bird_test
    ports:
      - "5432:5432"
    networks:
      - app-network

  # Express Server
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - ${PORT}:${PORT}
    networks:
      - app-network
    restart: always
    volumes:
      - .:/app
      - ./prisma:/app/prisma
      - ./logs:/root/.npm/_logs

networks:
  app-network:
    driver: bridge
